bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/1.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/2.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/3.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/4.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/5.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/6.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/7.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/8.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/9.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/10.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/11.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/12.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/13.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/14.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/15.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/16.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/17.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/18.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/19.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/20.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/21.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/22.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/23.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/24.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/25.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/26.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/27.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/28.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/29.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/30.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/31.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/32.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/33.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/34.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/35.sh
bash /home/elkallinymm/consolidationProject/biowulf_packaging/calculate/scripts/36.sh
